import { AfterContentInit, Component, Input, OnChanges, OnInit, SimpleChanges } from "@angular/core";
import { ObservedValueUnionFromArray } from "rxjs";
import { Product } from "src/app/Models/Product";

@Component({
    selector: "product-list",
    templateUrl: "./product-list.component.html",
    styleUrls: ["./product-list.component.css"]
})
export class ProductListComponent{
    selectedProduct : Product;
    products: Product[] = [
        {
            id: 1,
            name: "Nike React Infinity Run Flyknit",
            description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
            brand: "NIKE",
            gender: "MEN",
            category: "RUNNING",
            size: [6, 7, 8, 9, 10],
            color: ["White", "Blue", "Black"],
            price: 16000,
            is_in_inventory: true,
            discount: 10,
            items_left: 3,
            imageURL: "../assets/images/nike-react-infinity-run-flyknit.avif",
            slug: "nike-react-infinity-run-flyknit",
        },
        {
            id: 2,
            name: "Adidas Ultraboost 21",
            description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
            brand: "ADIDAS",
            gender: "WOMEN",
            category: "RUNNING",
            size: [7, 8, 9, 10, 11],
            color: ["Black", "Gray", "Pink"],
            price: 18000,
            is_in_inventory: true,
            items_left: 5,
            discount: 40,
            imageURL: "../assets/images/adidas-nmd-r1.jpeg",
            slug: "adidas-ultraboost-21",
        },
        {
            id: 3,
            name: "Puma RS-X Bold",
            description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
            brand: "PUMA",
            gender: "UNISEX",
            category: "CASUAL",
            size: [8, 9, 10, 11],
            color: ["White", "Red", "Blue"],
            price: 12000,
            is_in_inventory: false,
            items_left: 0,
            discount: 25,
            imageURL: "../assets/images/adidas-ultraboost-21.avif",
            slug: "puma-rs-x-bold",
        },
        {
            id: 4,
            name: "Reebok Nano X1",
            description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
            brand: "REEBOK",
            gender: "UNISEX",
            category: "CROSSFIT",
            size: [7, 8, 9, 10, 11],
            color: ["Black", "Yellow", "Green"],
            price: 15000,
            is_in_inventory: true,
            items_left: 8,
            discount: 15,
            imageURL: "../assets/images/reebok-classic-leather.jpeg",
            slug: "reebok-nano-x1",
        },
        {
            id: 5,
            name: "Under Armour HOVR Infinite 3",
            description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
            brand: "UNDER ARMOUR",
            gender: "WOMEN",
            category: "RUNNING",
            size: [6, 7, 8, 9],
            color: ["Gray", "Purple", "White"],
            price: 17000,
            is_in_inventory: true,
            items_left: 6,
            discount: 3,
            imageURL: "../assets/images/under-armour-hovr-infinite-3.webp",
            slug: "under-armour-hovr-infinite-3",
        },
        {
            id: 6,
            name: "ASICS Gel-Nimbus 23",
            description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
            brand: "ASICS",
            gender: "MEN",
            category: "RUNNING",
            size: [8, 9, 10, 11],
            color: ["Blue", "Yellow", "Black"],
            price: 15000,
            is_in_inventory: false,
            items_left: 0,
            discount: 90,
            imageURL: "../assets/images/asics-gel-nimbus-23.webp",
            slug: "asics-gel-nimbus-23",
        },
        {
            id: 7,
            name: "Brooks Ghost 14",
            description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
            brand: "BROOKS",
            gender: "WOMEN",
            category: "RUNNING",
            size: [7, 8, 9, 10, 11],
            color: ["Purple", "Black", "Gray"],
            price: 14000,
            is_in_inventory: true,
            items_left: 5,
            imageURL: "../assets/images/brooks-ghost-14.jpeg",
            slug: "brooks-ghost-14",
        },
        {
            id: 8,
            name: "Salomon Speedcross 5",
            description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
            brand: "SALOMON",
            gender: "UNISEX",
            category: "TRAIL RUNNING",
            size: [9, 10, 11, 12],
            color: ["Green", "Black", "Red"],
            price: 16000,
            is_in_inventory: true,
            items_left: 10,
            imageURL: "../assets/images/salomon-speedcross-5.jpeg",
            slug: "salomon-speedcross-5",
        },
        {
            id: 9,
            name: "Mizuno Wave Rider 25",
            description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
            brand: "MIZUNO",
            gender: "MEN",
            category: "RUNNING",
            size: [8, 9, 10, 11],
            color: ["Blue", "White", "Black"],
            price: 13000,
            is_in_inventory: true,
            items_left: 8,
            imageURL: "../assets/images/mizuno-wave-rider-25.jpeg",
            slug: "mizuno-wave-rider-25",
        },
        {
            id: 10,
            name: "Hoka One One Clifton 8",
            description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
            brand: "HOKA ONE ONE",
            gender: "WOMEN",
            category: "RUNNING",
            size: [6, 7, 8, 9],
            color: ["Gray", "Pink", "White"],
            price: 16000,
            is_in_inventory: true,
            items_left: 7,
            imageURL: "../assets/images/hoka-one-one-clifton-8.jpeg",
            slug: "hoka-one-one-clifton-8",

        },
        {
            id: 11,
            name: "Skechers GOrun Razor Excess",
            description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
            brand: "SKECHERS",
            gender: "MEN",
            category: "RUNNING",
            size: [9, 10, 11, 12],
            color: ["Black", "Blue", "Green"],
            price: 11000,
            is_in_inventory: true,
            items_left: 12,
            imageURL: "../assets/images/skechers-gorun-razor-excess.jpeg",
            slug: "skechers-gorun-razor-excess",
        },
        {
            id: 12,
            name: "Nike Air Zoom Pegasus 38",
            description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
            brand: "NIKE",
            gender: "WOMEN",
            category: "RUNNING",
            size: [7, 8, 9, 10, 11],
            color: ["White", "Purple", "Orange"],
            price: 15000,
            is_in_inventory: false,
            items_left: 0,
            imageURL: "../assets/images/nike-air-zoom-pegasus-38.jpeg",
            slug: "nike-air-zoom-pegasus-38",
        },
        {
            id: 13,
            name: "Adidas NMD R1",
            description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
            brand: "ADIDAS",
            gender: "UNISEX",
            category: "CASUAL",
            size: [8, 9, 10, 11],
            color: ["Black", "White", "Red"],
            price: 13000,
            is_in_inventory: true,
            items_left: 15,
            imageURL: "../assets/images/adidas-nmd-r1.jpeg",
            slug: "adidas-nmd-r1",
        },
        {
            id: 14,
            name: "Puma Future Rider",
            description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
            brand: "PUMA",
            gender: "MEN",
            category: "CASUAL",
            size: [7, 8, 9, 10],
            color: ["Blue", "Yellow", "Green"],
            price: 12000,
            is_in_inventory: true,
            items_left: 11,
            imageURL: "../assets/images/puma-future-rider.jpeg",
            slug: "puma-future-rider",
        },
        {
            id: 15,
            name: "Reebok Classic Leather",
            description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
            brand: "REEBOK",
            gender: "WOMEN",
            category: "CASUAL",
            size: [6, 7, 8, 9],
            color: ["White", "Pink", "Black"],
            price: 10000,
            is_in_inventory: true,
            items_left: 14,
            imageURL: "../assets/images/reebok-classic-leather.jpeg",
            slug: "reebok-classic-leather",
        },
        {
            id: 16,
            name: "Under Armour Charged Bandit 7",
            description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
            brand: "UNDER ARMOUR",
            gender: "MEN",
            category: "RUNNING",
            size: [8, 9, 10, 11],
            color: ["Black", "Gray", "Red"],
            price: 14000,
            is_in_inventory: true,
            items_left: 13,
            imageURL: "../assets/images/under-armour-charged-bandit-7.jpeg",
            slug: "under-armour-charged-bandit-7",
        },
        {
            id: 17,
            name: "ASICS Gel-Kayano 28",
            description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
            brand: "ASICS",
            gender: "WOMEN",
            category: "RUNNING",
            size: [7, 8, 9, 10],
            color: ["Blue", "White", "Pink"],
            price: 18000,
            is_in_inventory: true,
            items_left: 8,
            imageURL: "../assets/images/asics-gel-kayano-28.jpeg",
            slug: "asics-gel-kayano-28",
        },
        {
            id: 18,
            name: "Brooks Adrenaline GTS 22",
            description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
            brand: "BROOKS",
            gender: "MEN",
            category: "RUNNING",
            size: [9, 10, 11, 12],
            color: ["Black", "Blue", "Yellow"],
            price: 16000,
            is_in_inventory: true,
            items_left: 10,
            imageURL: "../assets/images/brooks-adrenaline-gts-22.jpeg",
            slug: "brooks-adrenaline-gts-22",
        },
        {
            id: 19,
            name: "Salomon XA Pro 3D V8",
            description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
            brand: "SALOMON",
            gender: "UNISEX",
            category: "TRAIL RUNNING",
            size: [8, 9, 10, 11],
            color: ["Black", "Red", "Green"],
            price: 14000,
            is_in_inventory: true,
            items_left: 12,
            imageURL: "../assets/images/salomon-xa-pro-3d-v8.jpeg",
            slug: "salomon-xa-pro-3d-v8",
        },
        {
            id: 20,
            name: "Mizuno Wave Inspire 17",
            description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
            brand: "MIZUNO",
            gender: "WOMEN",
            category: "RUNNING",
            size: [6, 7, 8, 9],
            color: ["Purple", "Gray", "White"],
            price: 13000,
            is_in_inventory: true,
            items_left: 12,
            imageURL: "../assets/images/mirzuno_wave_inspire_17.jpeg",
            slug: "mirzuno_wave_inspire_17",
        },
        {
            id: 21,
            name: "Hoka One One Rincon 3",
            description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
            brand: "HOKA ONE ONE",
            gender: "MEN",
            category: "RUNNING",
            size: [8, 9, 10, 11],
            color: ["Blue", "Yellow", "Black"],
            price: 14000,
            is_in_inventory: true,
            items_left: 9,
            imageURL: "../assets/images/hoka-one-one-rincon-3.jpeg",
            slug: "hoka-one-one-rincon-3",
        },
        {
            id: 22,
            name: "Saucony Guide 14",
            description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
            brand: "SAUCONY",
            gender: "WOMEN",
            category: "RUNNING",
            size: [7, 8, 9, 10],
            color: ["Gray", "Purple", "White"],
            price: 15000,
            is_in_inventory: true,
            items_left: 8,
            imageURL: "../assets/images/saucony-guide-14.jpeg",
            slug: "saucony-guide-14",
        },
        {
            id: 23,
            name: "New Balance 990v5",
            description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
            brand: "NEW BALANCE",
            gender: "MEN",
            category: "RUNNING",
            size: [9, 10, 11, 12],
            color: ["Black", "Gray", "Navy"],
            price: 18000,
            is_in_inventory: true,
            items_left: 7,
            imageURL: "../assets/images/new-balance-990v5.jpeg",
            slug: "new-balance-990v5",
        },
        {
            id: 24,
            name: "Under Armour Curry 8",
            description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
            brand: "UNDER ARMOUR",
            gender: "UNISEX",
            category: "BASKETBALL",
            size: [8, 9, 10, 11],
            color: ["White", "Blue", "Yellow"],
            price: 16000,
            is_in_inventory: true,
            items_left: 6,
            imageURL: "../assets/images/under-armour-curry-8.png",
            slug: "under-armour-curry-8",
        },
        {
            id: 25,
            name: "Nike Air Max 270",
            description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
            brand: "NIKE",
            gender: "WOMEN",
            category: "CASUAL",
            size: [6, 7, 8, 9],
            color: ["Black", "Pink", "Orange"],
            price: 15000,
            is_in_inventory: true,
            items_left: 10,
            imageURL: "../assets/images/nike-air-max-270.jpeg",
            slug: "nike-air-max-270",
        },
        {
            id: 26,
            name: "Adidas Superstar",
            description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
            brand: "ADIDAS",
            gender: "UNISEX",
            category: "CASUAL",
            size: [7, 8, 9, 10],
            color: ["White", "Black", "Gold"],
            price: 8000,
            is_in_inventory: true,
            items_left: 12,
            imageURL: "../assets/images/adidas-superstar.jpeg",
            slug: "adidas-superstar",
        },
        {
            id: 27,
            name: "Puma Calibrate Runner",
            description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
            brand: "PUMA",
            gender: "MEN",
            category: "RUNNING",
            size: [8, 9, 10, 11],
            color: ["Blue", "Gray", "Red"],
            price: 13000,
            is_in_inventory: true,
            items_left: 11,
            imageURL: "../assets/images/puma-calibrate-runner.jpeg",
            slug: "puma-calibrate-runner",
        },
        {
            id: 28,
            name: "Reebok Classic Nylon",
            description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
            brand: "REEBOK",
            gender: "WOMEN",
            category: "CASUAL",
            size: [6, 7, 8, 9],
            color: ["Black", "Pink", "White"],
            price: 7000,
            is_in_inventory: true,
            items_left: 15,
            imageURL: "../assets/images/reebok-classic-nylon.jpeg",
            slug: "reebok-classic-nylon",
        },
        {
            id: 29,
            name: "Skechers D'Lites",
            description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
            brand: "SKECHERS",
            gender: "UNISEX",
            category: "CASUAL",
            size: [8, 9, 10, 11],
            color: ["White", "Blue", "Red"],
            price: 9000,
            is_in_inventory: true,
            items_left: 9,
            imageURL: "../assets/images/skechers-dlites.jpeg",
            slug: "skechers-dlites",
        },
        {
            id: 30,
            name: "Converse Chuck Taylor All Star",
            description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
            brand: "CONVERSE",
            gender: "UNISEX",
            category: "CASUAL",
            size: [7, 8, 9, 10],
            color: ["Black", "White", "Red"],
            price: 6000,
            is_in_inventory: true,
            items_left: 18,
            imageURL: "../assets/images/converse-chuck-taylor-all-star.jpeg",
            slug: "converse-chuck-taylor-all-star",
        },
    ];

    allProduct:number = this.products.length;
    inStockProduct:number= this.products.filter(product=> product.is_in_inventory).length;
    outOfStockProduct:number = this.products.filter(product=> !product.is_in_inventory).length;
    selectedFilterRadioBtn:string = "all";

    @Input()
    currentSearchText:string="";


    handleOnSelectedRadioBtn(data:string){
       console.log("From parent component product-list: ",data);
       console.log("CurrentSearchText from product list component",this.currentSearchText);
       this.selectedFilterRadioBtn = data;
    }

    handleOnClickProductSelection(product:Product):void{
        this.selectedProduct=product;
        console.log("handle on click product selected",product.name);
    }

    
}  